module.exports = [
  {
    condominium_name: 'Condominio Central',
    condominium_country: 'Colombia',
    condominium_state: 'Cundinamarca',
    condominium_logo: 'https://example.com/logo1.jpg',
    condominiums_apartments_number: 50,
    imageUrl: 'https://example.com/image1.jpg',
    AdminId: null, // AdminId se asignará en la función de carga inicial
  },
  {
    condominium_name: 'Condominio Norte',
    condominium_country: 'Colombia',
    condominium_state: 'Antioquia',
    condominium_logo: 'https://example.com/logo2.jpg',
    condominiums_apartments_number: 60,
    imageUrl: 'https://example.com/image2.jpg',
    AdminId: null,
  },
  {
    condominium_name: 'Condominio Sur',
    condominium_country: 'Colombia',
    condominium_state: 'Valle del Cauca',
    condominium_logo: 'https://example.com/logo3.jpg',
    condominiums_apartments_number: 70,
    imageUrl: 'https://example.com/image3.jpg',
    AdminId: null,
  },
  {
    condominium_name: 'Condominio Este',
    condominium_country: 'Colombia',
    condominium_state: 'Atlántico',
    condominium_logo: 'https://example.com/logo4.jpg',
    condominiums_apartments_number: 80,
    imageUrl: 'https://example.com/image4.jpg',
    AdminId: null,
  },
  {
    condominium_name: 'Condominio Oeste',
    condominium_country: 'Colombia',
    condominium_state: 'Santander',
    condominium_logo: 'https://example.com/logo5.jpg',
    condominiums_apartments_number: 90,
    imageUrl: 'https://example.com/image5.jpg',
    AdminId: null,
  },
  {
    condominium_name: 'Condominio Montaña',
    condominium_country: 'Colombia',
    condominium_state: 'Boyacá',
    condominium_logo: 'https://example.com/logo6.jpg',
    condominiums_apartments_number: 100,
    imageUrl: 'https://example.com/image6.jpg',
    AdminId: null,
  },
];
